blank_issues_enabled: true
contact_links:
  - name: プロジェクトドキュメント
    url: https://github.com/darallium/SecHack365-RD/semi/wiki
    about: プロジェクトの詳細情報やガイドライン
  - name: 調査・研究ガイドライン
    url: https://github.com/darallium/SecHack365-RD/blob/main/CLAUDE.md
    about: 調査重視の研究方針とプロジェクト指針
